#!/bin/bash

# if , elif, else Example

a=10
b=10

if [ $a -gt $b ]
then
    echo a is greater

elif [ $a == $b ]
	then    
		echo a and b are equal

else
	echo b is greater
fi

#Switch case example

CARS="audi"

case "$CARS" in
    #case 1
    "mercedes") echo "Headquarters - Affalterbach, Germany" ;;

    #case 2
    "audi") echo "Headquarters - Ingolstadt, Germany" ;;

    #case 3
    "bmw") echo "Headquarters - Chennai, Tamil Nadu, India" ;;
esac

#for loop example

for i in {1..10};
do echo $i;
done
